// Code generated by .github/scripts/gen_tests; DO NOT EDIT.
// Auto-discovered smoke tests for side-effect-free helpers.
package tlsfrag

import "testing"

func TestGenerated_FindLastDot(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): FindLastDot")
		}
	}()
	_, _ = FindLastDot(nil, 0, 0)
}

func TestGenerated_makeRecord(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): makeRecord")
		}
	}()
	_ = makeRecord(nil, nil)
}

func TestGenerated_splitAndAppend(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): splitAndAppend")
		}
	}()
	splitAndAppend(nil, nil, 0, nil)
}
