// Code generated by .github/scripts/gen_tests; DO NOT EDIT.
// Auto-discovered smoke tests for side-effect-free helpers.
package common

import "testing"

func TestGenerated_ConfigCertDir(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): ConfigCertDir")
		}
	}()
	_ = ConfigCertDir("")
}

func TestGenerated_ConfigProxyMarker(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): ConfigProxyMarker")
		}
	}()
	_ = ConfigProxyMarker("")
}
