// Code generated by .github/scripts/gen_tests; DO NOT EDIT.
// Auto-discovered smoke tests for side-effect-free helpers.
package proxy

import "testing"

func TestGenerated_certNames(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): certNames")
		}
	}()
	_ = certNames(nil)
}

func TestGenerated_dedupeDialCandidates(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): dedupeDialCandidates")
		}
	}()
	_ = dedupeDialCandidates(nil)
}

func TestGenerated_defaultDNSNodes(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): defaultDNSNodes")
		}
	}()
	_ = defaultDNSNodes()
}

func TestGenerated_dnsMatch(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): dnsMatch")
		}
	}()
	_ = dnsMatch("", "")
}

func TestGenerated_domainMatchScore(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): domainMatchScore")
		}
	}()
	_ = domainMatchScore("", "")
}

func TestGenerated_ensureLegacyCloudflareProfile(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): ensureLegacyCloudflareProfile")
		}
	}()
	_ = ensureLegacyCloudflareProfile(nil)
}

func TestGenerated_generateID(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): generateID")
		}
	}()
	_ = generateID()
}

func TestGenerated_gfwListCachePath(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): gfwListCachePath")
		}
	}()
	_ = gfwListCachePath("")
}

func TestGenerated_hostMatchesDomain(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): hostMatchesDomain")
		}
	}()
	_ = hostMatchesDomain("", "")
}

func TestGenerated_isHopByHopHeader(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): isHopByHopHeader")
		}
	}()
	_ = isHopByHopHeader("")
}

func TestGenerated_matchesAllowedNames(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): matchesAllowedNames")
		}
	}()
	_ = matchesAllowedNames(nil, nil)
}

func TestGenerated_matchesAllowedSuffixes(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): matchesAllowedSuffixes")
		}
	}()
	_ = matchesAllowedSuffixes(nil, nil)
}

func TestGenerated_matchesSPKI(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): matchesSPKI")
		}
	}()
	_ = matchesSPKI(nil, nil)
}

func TestGenerated_migrateLegacyECHRules(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): migrateLegacyECHRules")
		}
	}()
	_ = migrateLegacyECHRules(nil, nil)
}

func TestGenerated_normalizeDNSMode(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): normalizeDNSMode")
		}
	}()
	_ = normalizeDNSMode("")
}

func TestGenerated_normalizeDomainsForKey(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): normalizeDomainsForKey")
		}
	}()
	_ = normalizeDomainsForKey(nil)
}

func TestGenerated_normalizeECHProfile(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): normalizeECHProfile")
		}
	}()
	normalizeECHProfile(nil)
}

func TestGenerated_resolveUpstreamHost(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): resolveUpstreamHost")
		}
	}()
	_ = resolveUpstreamHost("", "")
}

func TestGenerated_rewriteUTLSALPN(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): rewriteUTLSALPN")
		}
	}()
	rewriteUTLSALPN(nil, nil)
}

func TestGenerated_spkiHashBase64(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Skipf("zero-value call panicked (not smoke-testable): spkiHashBase64")
		}
	}()
	_ = spkiHashBase64(nil)
}
